### ISSUE TITLE
GPG error during the pritunl setup on ubuntu 22.04

### ISSUE THREAD

**Issue by gmourahub** [nathanielvarona/pritunl-client-github-action#206]
### Issue Description
During the setup process, this error appears:

```
deb https://repo.pritunl.com/stable/apt jammy main
gpg: WARNING: nothing exported
W: GPG error: https://repo.pritunl.com/stable/apt jammy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7AE645C0CF8E292A
E: The repository 'https://repo.pritunl.com/stable/apt jammy InRelease' is not signed.
/home/runner/work/_actions/nathanielvarona/pritunl-client-github-action/v1/pritunl-client.sh: line 334: pritunl-client: command not found
It appears that the profile file cannot be loaded.
Error: Process completed with exit code 1.
```

Code:

```
jobs:
  tests:
    runs-on: ubuntu-latest
    environment: testing

    steps:
      - name: Setup Pritunl Profile and Start VPN Connection
        uses: nathanielvarona/pritunl-client-github-action@v1
        with:
          profile-file: ${{ secrets.PRITUNL_PROFILE_FILE }}
          profile-pin: ${{ secrets.PRITUNL_PROFILE_PIN }}
```

### It has been used with the following parameters:

**Runner Virtual Environments:**
- Linux
  - [X] Ubuntu 22.04
  - [ ] Ubuntu 20.04
- macOS
  - [ ] macOS 12
  - [ ] macOS 11
- Windows
  - [ ] Windows 2022
  - [ ] Windows 2019

**VPN Modes:**
- [x] OpenVPN (ovpn) 
- [ ] WireGuard (wg)

**Client Versions:**
- [x] Installed from the package manager 
- Version specific
  
  - [ ] 1.3.3883.60

**Start Connection:** *If the connection is started on the setup step.*
- [x]  True 
- [ ] False

**Runner Types:**
- [x] Tested on GitHub-hosted runner 
- Tested on Self-Hosted runner

  *If it runs on a self-hosted runner:*
  - [ ] Manage Self-hosted
  - [ ] Action Runner Controller (ARC) (a Kubernetes Operator)

**Comment by nathanielvarona** [comment]
@gmourahub, thank you for the reported issue.

Upon checking with my test repo, it is currently working now.

<img width="1366" alt="Screenshot 2024-06-21 at 1 49 34 AM" src="https://github.com/nathanielvarona/pritunl-client-github-action/assets/194283/f19e38a9-1362-46ed-99c9-0593aa0c27a6">

Further investigation of what might have caused the issue, is probably the https://keyserver.ubuntu.com/ downtime.

<img width="1180" alt="Screenshot 2024-06-21 at 1 46 18 AM" src="https://github.com/nathanielvarona/pritunl-client-github-action/assets/194283/1c645388-4f8e-4e3e-8000-e7440a42f867">
<img width="1036" alt="Screenshot 2024-06-21 at 1 46 53 AM" src="https://github.com/nathanielvarona/pritunl-client-github-action/assets/194283/fc3c974c-c349-49a8-9757-256b0aa1a2d8">
<img width="1046" alt="Screenshot 2024-06-21 at 1 48 13 AM" src="https://github.com/nathanielvarona/pritunl-client-github-action/assets/194283/00a46a18-b208-4393-bc41-f47975d21d95">

Uptime/Status Monitoring Sites:

* https://statusgator.com/services/canonical/keyserverubuntucom
* https://status.canonical.com/

**Pro Tip:**

To prevent this kind of situation, I would recommend you change specific settings in your action steps to install the client from a `.deb` file from GitHub Releases.

The standalone installation will not attempt to fetch the GPG key from the keyserver since we already verified the authenticity of the DEB file from its source (The https://github.com/pritunl/pritunl-client-electron)

```yaml
- name: Setup Pritunl Profile and Start VPN Connection
  uses: nathanielvarona/pritunl-client-github-action@v1
  with:
    profile-file: ${{ secrets.PRITUNL_PROFILE_FILE }}
    profile-pin: ${{ secrets.PRITUNL_PROFILE_PIN }}
    client-version: 1.3.3883.60
```

> [!NOTE]
> Frequently check the https://github.com/pritunl/pritunl-client-electron/releases for later releases

Please let me know if you still encounter the same issue.

Thanks,
