### ISSUE TITLE
pritunl-client: command not found

### ISSUE THREAD

**Issue by JosueCL11** [nathanielvarona/pritunl-client-github-action#209]
Good afternoon, a question, I have been using githubaction: nathanielvarona/pritunl-client-github-action@v1, and everything had been working correctly, but until today it gave me this error, is there something I need?

<img width="1307" alt="Captura de pantalla 2024-07-25 a la(s) 5 22 08 p m" src="https://github.com/user-attachments/assets/6335c4bb-d97a-4d69-828e-e655e3a6766e">

**Comment by JosueCL11** [comment]
This is mi definition :     

  - name: Setup Pritunl Profile and Start VPN Connection
        uses: nathanielvarona/pritunl-client-github-action@v1
        with:
          profile-file: ${{ secrets.PRITUNL_PROFILE_FILE }}
          profile-pin: ${{ secrets.PRITUNL_PROFILE_PIN }}

**Comment by Alex-Munro** [comment]
I'm getting the same error across all my actions that use this step:
``` yaml
      - name: Setup Pritunl Profile and Start VPN Connection
        uses: nathanielvarona/pritunl-client-github-action@v1
        with:
          profile-file: ${{ secrets.PRITUNL_PROFILE_FILE }}
          profile-pin: ${{ secrets.PRITUNL_PROFILE_PIN }}
```

**Comment by nathanielvarona** [comment]
Hello @JosueCL11 and @Alex-Munro, thank you for reporting the issue.

This issue is related to the **GitHub Actions Apt Repositories List and Cache**. 
This is solely from the **GitHub Actions Virtual Environment Images** releases issue. 

There is a fix for this, however, I need to validate and fully test it.
(As much as possible I won't touch anything in the GitHub action Virtual Environment to maintain the integrity of this action) 

For now, I would suggest using a specific client installation. This method obtains the `pritunl-client` package from the https://github.com/pritunl/pritunl-client-electron/releases instead of the https://repo.pritunl.com/stable/apt/dists/jammy/.

**Here is an example:**
```yaml
- name: Setup Pritunl Profile
  id: pritunl-connection
  uses: nathanielvarona/pritunl-client-github-action@v1
  with:
    profile-file: ${{ secrets.PRITUNL_PROFILE_FILE }}
    profile-pin: ${{ secrets.PRITUNL_PROFILE_PIN }}
    client-version: 1.3.3883.60 # <-- PLEASE ADD THIS INPUT IN YOUR ACTION
```

**My tests earlier:**
Test # 1: Failed - Installation using Apt Registry
Test # 2: Passing - Specify the Client Version
https://github.com/nathanielvarona/gha-pub-test-repo/actions/workflows/connection-tests-manual-install-only.yml

Let me know if this fixes the issue on your side.

Again good day and have a nice weekend.
