### ISSUE TITLE
As a user, I want to connect to multiple servers using a single profile.

### ISSUE THREAD

**Issue by nathanielvarona** [nathanielvarona/pritunl-client-github-action#93]
Create a feature that allows multiple established connections.

Scenario:
* I want to use GitHub Actions to build software releases for different units within the organization and distribute them to private storage networks.

Example Manifest:
```
- name: Setup Pritunl Profile and Start VPN Connection
  uses: nathanielvarona/pritunl-client-github-action@v1
  with:
    profile-file: ${{ secrets.PRITUNL_PROFILE_FILE }}
    profile-server: 
      - 'quality-assurance' # Connection 1
      - 'sales-marketing' # Connection 2
      - 'research-development' # Connection 3
```

Architecture Results:

```
                      +----------------------+  Connection 3                                                                     +--------------------------+
                      |   Profile Server 3   | =======================================================#                          |     Pritunl Server 3     | -------------------------------------------+
                      +----------------------+                                                        H                          +--------------------------+                                            |
                        ^                                                                             H                            ^                                                                     |
                        |                                                                             H                            H Connection 3                                                        |
                        |                                                                             v                            H                                                                     v
+---------------+     +----------------------+                 +------------------+  Connection 1   +----------------------+     +--------------------------+  Connection 1   +------------------+     +--------------+
| GitHub Action | --> | Pritun Profile Setup | --------------> | Profile Server 1 | ==============> | Pritunl Server Infra | --> | Pritunl User-Org-Network | ==============> | Pritunl Server 1 | --> | Host Cluster |
+---------------+     +----------------------+                 +------------------+                 +----------------------+     +--------------------------+                 +------------------+     +--------------+
                        |                                                                             ^                            H                                                                     ^
                        |                                                                             H                            H Connection 2                                                        |
                        v                                                                             H                            v                                                                     |
                      +----------------------+  Connection 2                                          H                          +--------------------------+                                            |
                      |   Profile Server 2   | =======================================================#                          |     Pritunl Server 2     | -------------------------------------------+
                      +----------------------+                                                                                   +--------------------------+

```

**Comment by nathanielvarona** [comment]
GitHub Actions workflow inputs do not support Yaml List and only support String, Number, or Boolean.
Therefore, the widely accepted way to pass multiple values for an input is using a single string separated by commas.

Example:
```yml
- name: Setup Pritunl Profile and Start VPN Connection
  uses: nathanielvarona/pritunl-client-github-action@v1
  with:
    profile-file: ${{ secrets.PRITUNL_PROFILE_FILE }}
    profile-server: 'quality-assurance, sales-marketing, research-development'
```

And if we want to specify a single specific server, we can use:
```yml
- name: Setup Pritunl Profile and Start VPN Connection
  uses: nathanielvarona/pritunl-client-github-action@v1
  with:
    profile-file: ${{ secrets.PRITUNL_PROFILE_FILE }}
    profile-server: quality-assurance
```
